// Products
export const REQUEST_PRODUCTS       = 'REQUEST_PRODUCTS'
export const PRODUCTS_LOADING_COMPLETED     = 'PRODUCTS_LOADING_COMPLETED'
export const FETCH_ALL_PRODUCTS     = 'FETCH_ALL_PRODUCTS'
export const RECEIVE_PRODUCTS       = 'RECEIVE_PRODUCTS'
export const RECEIVE_CLUSTERS       = 'RECEIVE_CLUSTERS'
export const ENABLE_PRODUCTS_FILTER = 'ENABLE_PRODUCTS_FILTER'
export const CLEAR_PRODUCTS_FILTER  = 'CLEAR_PRODUCTS_FILTER'
export const FILTER_PRODUCTS        = 'FILTER_PRODUCTS'
export const FILTER_PRODUCTS_ERROR  = 'FILTER_PRODUCTS_ERROR'

// Cart
export const REQUEST_CART_UPDATE_ADD      = 'REQUEST_CART_UPDATE_ADD'
export const REQUEST_CART_UPDATE_REMOVE   = 'REQUEST_CART_UPDATE_REMOVE'
export const REQUEST_CART_UPDATE_SHIPPING = 'REQUEST_CART_UPDATE_SHIPPING'

export const CALCULATE_CART_TOTALS = 'CALCULATE_CART_TOTALS'
export const ADD_TO_CART           = 'ADD_TO_CART'
export const SET_IN_CART           = 'SET_IN_CART'
export const REMOVE_FROM_CART      = 'REMOVE_FROM_CART'
export const ADD_TO_CART_ERROR     = 'ADD_TO_CART_ERROR'
export const ADD_TO_CART_ARRAY     = 'ADD_TO_CART_ARRAY'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

export const SELECT_PROMO       = 'SELECT_PROMO'
export const SELECT_PROMO_ERROR = 'SELECT_PROMO_ERROR'
export const SELECT_CLUBTYPE    = 'SELECT_CLUBTYPE'

export const SET_GRATUITY    = 'SET_GRATUITY'

// export const INCREMENT = 'INCREMENT';
// export const DECREMENT = 'DECREMENT';

// Members
export const REQUEST_MEMBER_BY_EMAIL = 'REQUEST_MEMBER'
export const RECEIVE_MEMBER          = 'RECEIVE_MEMBER'
export const UPDATE_MEMBER_INFO      = 'UPDATE_MEMBER_INFO'

// User
// export const REQUEST_USER_AUTH = 'REQUEST_USER_AUTH'
export const RECEIVE_USER_AUTH = 'RECEIVE_USER_AUTH'
export const LOGIN             = 'LOGIN'
export const LOGIN_PENDING     = 'LOGIN_PENDING'
export const LOGIN_REQUEST     = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS     = 'LOGIN_SUCCESS'
export const LOGIN_ERROR       = 'LOGIN_ERROR'
export const LOGOUT            = 'LOGOUT'

// options
export const REQUEST_STORES       = 'REQUEST_STORES'
export const RECEIVE_STORES       = 'RECEIVE_STORES'
export const SELECT_STORE         = 'SELECT_STORE'
export const REQUEST_STORES_ERROR = 'REQUEST_STORES_ERROR'

export const REQUEST_STORE       = 'REQUEST_STORE'
export const RECEIVE_STORE       = 'RECEIVE_STORE'
export const REQUEST_STORE_ERROR = 'REQUEST_STORE_ERROR'

export const REQUEST_REFERRERS       = 'REQUEST_REFERRERS'
export const RECEIVE_REFERRERS       = 'RECEIVE_REFERRERS'
export const SELECT_REFERRER         = 'SELECT_REFERRER'
export const REQUEST_REFERRERS_ERROR = 'REQUEST_REFERRERS_ERROR'

export const REQUEST_PREFS       = 'REQUEST_PREFS'
export const RECEIVE_PREFS       = 'RECEIVE_PREFS'
export const REQUEST_PREFS_ERROR = 'REQUEST_PREFS_ERROR'

export const REQUEST_CONFIG       = 'REQUEST_CONFIG'
export const RECEIVE_CONFIG       = 'RECEIVE_CONFIG'
export const REQUEST_CONFIG_ERROR = 'REQUEST_CONFIG_ERROR'

export const REQUEST_SALESREPS       = 'REQUEST_SALESREPS'
export const RECEIVE_SALESREPS       = 'RECEIVE_SALESREPS'
export const SELECT_SALESREP         = 'SELECT_SALESREP'
export const REQUEST_SALESREPS_ERROR = 'REQUEST_SALESREPS_ERROR'

export const REQUEST_CLUBTYPES       = 'REQUEST_CLUBTYPES'
export const RECEIVE_CLUBTYPES       = 'RECEIVE_CLUBTYPES'
export const REQUEST_CLUBTYPES_ERROR = 'REQUEST_CLUBTYPES_ERROR'

export const REQUEST_PROMOS       = 'REQUEST_PROMOS'
export const RECEIVE_PROMOS       = 'RECEIVE_PROMOS'
export const REQUEST_PROMOS_ERROR = 'REQUEST_PROMOS_ERROR'

export const REQUEST_COUPON       = 'REQUEST_COUPON'
export const RECEIVE_COUPON       = 'RECEIVE_COUPON'
export const REQUEST_COUPON_ERROR = 'REQUEST_COUPON_ERROR'

export const REQUEST_SHIPPING_OPTIONS       = 'REQUEST_SHIPPING_OPTIONS'
export const RECEIVE_SHIPPING_OPTIONS       = 'RECEIVE_SHIPPING_OPTIONS'
export const REQUEST_SHIPPING_OPTIONS_ERROR = 'REQUEST_SHIPPING_OPTIONS_ERROR'

export const REQUEST_SALESTAX_INFO = 'REQUEST_SALESTAX_INFO'
export const RECEIVE_SALESTAX_INFO = 'RECEIVE_SALESTAX_INFO'

export const RECEIVE_PROMO_CATALOG_UPDATE       = 'RECEIVE_PROMO_CATALOG_UPDATE'
// export const REQUEST_PROMO_CATALOG_UPDATE = 'REQUEST_PROMO_CATALOG_UPDATE'
export const REQUEST_PROMO_CATALOG_UPDATE_ERROR = 'REQUEST_PROMO_CATALOG_UPDATE_ERROR'

export const REQUEST_ZIP_CODE_BILLING = 'REQUEST_ZIP_CODE_BILLING'
export const REQUEST_ZIP_CODE_SHIPPING = 'REQUEST_ZIP_CODE_SHIPPING'

//customer
// export const REQUEST_CUSTOMER_BY_EMAIL = 'REQUEST_CUSTOMER'
// export const RECEIVE_CUSTOMER          = 'RECEIVE_CUSTOMER'